{{- if .Values.ingress.basicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ .Values.ingress.basicAuth.htpasswd | b64enc }}
{{- end }}