nameOverride: envoy-gateway

external:
  # enable external traffic
  enabled: false

  # redirect http traffic to https
  # applies on all external traffic.
  # if you want to specify a service on port 80, create another httproute
  # a more specific route will be resolved first
  httpsRedirect:
    enabled: true

  # CHANGE THIS FOR PRODUCTION to a letsencrypt-prod clusterissuer
  clusterIssuerName: self-signed
  service:
    annotations:
      # prevents errors when deleting clusters, leave as true
      loadbalancer.openstack.org/keep-floatingip: "true"
      # Set loadbalancing method: ROUND_ROBIN, LEAST_CONNECTIONS, SOURCE_IP, SOURCE_IP_PORT
      loadbalancer.openstack.org/lb-method: ROUND_ROBIN
      # Client inactivity timeout in milliseconds
      loadbalancer.openstack.org/timeout-client-data: "60000"
      # Set true to enable X-Forwarded-For Headers for HTTP
      loadbalancer.openstack.org/x-forwarded-for: "false"
    loadbalancerIP: null

  deployment:
    replicas: 3
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  listeners:
    # define separate listeners here for all externally accessible services (by hostname)

    # HTTP listener - accept routes from all namespaces
    #  - name: http
    #    protocol: HTTP
    #    port: 80
    #    allowedRoutes:
    #      namespaces:
    #        from: All

    # HTTPS listener - accepts routes from all namespaces
    # only routes matching wildcard hostname, certificate auto-generated and terminated at gateway
    # services downstream either communicate via port 80, or we setup a BackendTLSPolicy for HTTPS traffic
    # secret is autogenerated and managed by cert-manager in envoy namespace

    #  - name: example-wildcard-https
    #    protocol: HTTPS
    #    port: 443
    #    tls:
    #      secretName: example-tls
    #      mode: Terminate
    #    hostname: "*.example.com"
    #    allowedRoutes:
    #      namespaces:
    #        from: All

    # HTTPS listener - accepts routes from all namespaces
    # only routes matching exact hostname - takes precedence over wildcard,
    # TLS passthrough means that gateway won't terminate TLS, instead the downstream service will
    # TLS certs must be configured by service downstream

    #  - name: example-passthrough-https
    #    protocol: HTTPS
    #    port: 443
    #    tls:
    #      mode: Passthrough
    #    hostname: "another.example.com""
    #    allowedRoutes:
    #      namespaces:
    #        from: All

internal:
  clusterIssuerName: self-signed

  # redirect http traffic to https
  # applies on all internal traffic.
  # if you want to specify a service on port 80, create another httproute
  # a more specific route will be resolved first
  httpsRedirect:
    enabled: true

  service:
    annotations:
      # prevents errors when deleting clusters, leave as true
      loadbalancer.openstack.org/keep-floatingip: "true"
      # Set loadbalancing method: ROUND_ROBIN, LEAST_CONNECTIONS, SOURCE_IP, SOURCE_IP_PORT
      loadbalancer.openstack.org/lb-method: ROUND_ROBIN
      # Client inactivity timeout in milliseconds
      loadbalancer.openstack.org/timeout-client-data: "60000"
      # Set true to enable X-Forwarded-For Headers for HTTP
      loadbalancer.openstack.org/x-forwarded-for: "false"
    loadbalancerIP: null

  deployment:
    replicas: 3
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  listeners:
    # define separate listeners here for all internally accessible services (by hostname)

# envoy-gateway helm chart values
gateway-helm:
  deployment:
    replicas: 1

  # enable "Backend" resources to be created
  # allows insecure TLS connection to backend HTTPS services
  #config:
  #  envoyGateway:
  #    extensionApis:
  #      enableBackend: true
