apiVersion: v2
name: stfc-cloud-argocd
dependencies:
  # https://github.com/argoproj/argo-helm/releases
  - name: argo-cd
    version: 9.4.7
    repository: https://argoproj.github.io/argo-helm
version: 2.0.0
