apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: fluent-bit-filters
spec:
  filters:
    - kubernetes:
        name: k8s-filter
        enable: true
        label: false
    - containerd:
        name: containerd-filter
        enable: true
    - systemd:
        name: systemd-filter
        enable: true