apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  annotations:
    fluentbit.io/exclude: "true"
spec:
  volumes:
    - name: host-proc
      hostPath:
        path: /proc/
    - name: host-sys
      hostPath:
        path: /sys/
    - name: host-buffer
      hostPath:
        path: /tmp/fluent-bit-buffer

  volumeMounts:
    - mountPath: /host/sys
      mountPropagation: HostToContainer
      name: host-sys
      readOnly: true
    - mountPath: /host/proc
      mountPropagation: HostToContainer
      name: host-proc
      readOnly: true
    - mountPath: /host/fluent-bit-buffer
      mountPropagation: HostToContainer
      name: host-buffer

  service:
    storage:
      path: "/host/fluent-bit-buffer/"
      backlogMemLimit: "50MB"
      checksum: "off"
      deleteIrrecoverableChunks: "on"
      maxChunksUp: 128
      sync: normal