{{- if .Values.opensearchCredentials}}
{{- with .Values.opensearchCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
type: Opaque
stringData:
  username: {{ .username }}
  password: {{ .password }}
{{- end }}
{{- end }}