apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal-proxy
  namespace: {{ include "envoy-gateways.namespace" . }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations: 
          {{- toYaml  .Values.internal.service.annotations | nindent 10}}
        loadBalancerIP: {{.Values.internal.service.loadBalancerIP}}
      envoyDeployment:
        replicas: {{ .Values.internal.deployment.replicas }}
        container:
          resources:
            requests:
              cpu: {{ .Values.internal.deployment.resources.requests.cpu }}
              memory: {{ .Values.internal.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.internal.deployment.resources.limits.cpu }}
              memory: {{ .Values.internal.deployment.resources.limits.memory }}
---

apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: internal
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: internal-proxy
    namespace: {{ include "envoy-gateways.namespace" .}}
  