{{- if index .Values "le-prod" "enabled" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ index .Values "le-prod" "email"}}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod-account-key
    solvers:
    - http01:
        ingress:
          # Assuming you have used the CAPI Addons Ingress Controller
          ingressClassName: nginx
{{- end }}
