
{{- if .Values.certificate.admin.enabled -}}
{{- $clusterName := index .Values "opensearch-cluster" "cluster" "name" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{$clusterName}}-admin-cert
  namespace: {{.Release.Namespace}}
spec:
  subject:
    organizationalUnits: [{{ $clusterName }}] # OU
  commonName: admin # CN
  secretName: {{$clusterName}}-admin-tls
  duration: 87600h0m0s # 10yr
  renewBefore: 8760h0m0s # 1yr
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    {{- with .Values.certificate.admin.issuer.group }}
    group: {{ . | quote }}
    {{- end }}
    kind: {{ .Values.certificate.admin.issuer.kind | quote }}
    name: {{ .Values.certificate.admin.issuer.name | quote }}
{{- end }}


