{{- if .Values.harbor.internalTLS.enabled -}}
{{- $svcCore := printf "%s-portal" (include "harbor.fullname" .) -}}
{{- $svcPortal :=  printf "%s-core" (include "harbor.fullname" .) -}}
{{- if eq .Values.harbor.expose.type "route" -}}


apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: {{ $svcCore }}-backend-tls-policy
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ $svcCore }}
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: {{ .Values.caBundleName | default "internal-bundle" }}
    hostname: {{ $svcCore }}.{{ .Release.Namespace }}.svc.cluster.local

---

apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: {{ $svcPortal }}-portal-backend-tls-policy
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ $svcPortal }}
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: {{ .Values.caBundleName | default "internal-bundle" }}
    hostname: {{ $svcPortal }}.{{ .Release.Namespace }}.svc.cluster.local

{{- end }}
{{- end }}