{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-backup-secret
type: Opaque
stringData:
  accesskey: {{ .Values.backup.accesskey | quote }}
  secretkey: {{ .Values.backup.secretkey | quote }}
{{- end }}
