{{- if .Values.harbor.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ .Values.harbor.basicAuth.htpasswd | b64enc }}
{{- end }}