{{- if .Values.harbor.internalTLS.enabled }}
{{- if eq .Values.harbor.internalTLS.certSource "secret" -}}

{{- $services := list "core" "jobservice" "registry" "portal" "trivy" }}

{{- range $svc := $services }}
{{- $cfg := index $.Values.harbor.internalTLS $svc }}
{{- $secret := $cfg.secretName }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $secret }}-cert
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ $secret }}
  issuerRef:
    name: {{ $.Values.internalCertIssuer | default "internal-ca"}}}
    kind: Issuer
    group: cert-manager.io
  commonName: harbor-{{ $svc }}
  dnsNames:
    - harbor-{{ $svc }}
    - harbor-{{ $svc }}.{{ $.Release.Namespace }}.svc
    - harbor-{{ $svc }}.{{ $.Release.Namespace }}.svc.cluster.local

{{- end }}

{{- end }}
{{- end }}
