{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: harbor-backup-weekly
spec:
  schedule: "0 17 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aws-cli
              image: amazon/aws-cli:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  aws s3 sync {{ .Values.backup.sourceBucket }} {{ .Values.backup.destination.weekly }} \
                  --endpoint-url {{ .Values.backup.endpoint }} --exact-timestamps --delete
              env:
                - name: ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: harbor-backup-secret
                      key: accesskey
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: harbor-backup-secret
                      key: secretkey
          restartPolicy: OnFailure
{{- end }}