{{- if .Values.httpsRedirect.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "envoy-gateways.name" .}}-redirect
  namespace: {{ include "envoy-gateways.namespace" .}}

spec:
  parentRefs:
    - name: {{ include "envoy-gateways.name" .}}-internal
      namespace: {{ include "envoy-gateways.namespace" .}}
    
    {{- if .Values.external.enabled }}
    - name: {{ include "envoy-gateways.name" .}}-external
      namespace: {{ include "envoy-gateways.namespace" .}}
    {{- end }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 308
{{- end }}