replicaCount: 3
nameOverride: docker-registry

image:
  repository: registry
  tag: 3.0.0

service:
  name: registry
  port: 5000

# for version 2
# for version 3 - /etc/distribution
configPath: /etc/docker/registry

internalTLS:
  enabled: true
  # use existing secret, if defined, uses this over certificate-generated secret
  # existingSecret: "my-secret"

  # generate a cert-manager certificate
  certificate:
    enabled: true
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: internal-ca-issuer

# to allow internalTLS to work with gateway api
# specify the configmap "internal-bundle" which is managed by "trust-manager"
backendTLSPolicy:
  enabled: true
  caBundleName: internal-bundle

httproute:
  # Enable HTTPRoute resource for docker-registry (Gateway API)
  enabled: true
  # -- Additional HTTPRoute labels
  labels: {}
  # -- Additional HTTPRoute annotations
  annotations: {}
  # -- Gateway API parentRefs for the HTTPRoute
  ## Must reference an existing Gateway
  parentRefs: []
    #  - name: gateway-external
    #    namespace: envoy-gateway-system
    #    sectionName: dockerhub
    #    group: gateway.networking.k8s.io
    #    kind: Gateway

  # -- List of hostnames for the HTTPRoute
  hostnames: []
  # - dockerhub.example.com

  # -- HTTPRoute rules configuration
  rules:
    # Rule 1: Normal routing for /v2
    - matches:
        - path:
            type: PathPrefix
            value: /v2
      timeouts:
        request: 900s
        backendRequest: 900s

  extraRules:
    # Rule 2: Redirect everything not starting with /v2 -> /v2
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /v2/
            statusCode: 301

ingress:
  enabled: false

# we'll default to S3
persistence:
  enabled: false
  # existingClaim: claim-name
  accessMode: "ReadWriteOnce"
  size: 10Gi
  storageClass: longhorn

# set the type of filesystem to use: filesystem or s3
storage: s3

# Options for s3 storage type if .Values.storage=s3:
s3:
  bucket: my-bucket
  regionEndpoint: s3.example.com
  encrypt: false
  secure: true
  region: RegionOne

## Pass extra environment variables to the Docker Registry container.
extraEnvVars:
# - name: EXTRA_VAR_1
#  value: extra-var-value-1
# - name: EXTRA_VAR_2
#   value: extra-var-value-2

# remote url for pull-through cache
proxy:
  remoteURL: https://registry-1.docker.io
  # username and password to remoteurl docker repo to cache from
  username: user1
  password: pass1

metrics:
  enabled: true
  port: 5001
  # Create a prometheus-operator servicemonitor
  serviceMonitor:
    enabled: true

# Config to pass to
configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
    tls:
      certificate: /etc/ssl/docker/tls.crt
      key: /etc/ssl/docker/tls.key
    debug:
      addr: :5001
      prometheus:
        enabled: true
        path: /metrics
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3

# to enable HA, all registry copies must have a random 16 digit alphanumeric set
# if you don't pass this, one will be created but you may run into argoCD out-of-sync issues
secrets:
  # # (Optional): Use an existing secret for haSharedSecret and proxy secrets
  # # secretRef: <secret-name>
  haSharedSecret: foobar12
  # to enable s3 persistent storage - pass access and storage keys and set .Values.storage=s3
  # Secrets for S3 access and secret keys
  #   s3:
  #     # (Optional): Use an existing secret for S3 creds
  #     # secretRef: <secret-name>
  s3:
    accessKey: awsaccesskey
    secretKey: awssecretkey
