replicaCount: 1

image:
  repository: registry
  tag: 2.7.1

service:
  name: registry
  port: 5000

ingress:
  enabled: false
  ingressClassName: nginx
  path: /
  # Used to create an Ingress record.
  hosts:
    - dockerhub.example.com
  annotations:
    cert-manager.io/cluster-issuer: "self-signed"  
  tls:
    - hosts:
       - dockerhub.example.com

persistence:
  enabled: false
# existingClaim: claim-name
  accessMode: 'ReadWriteOnce'
  size: 10Gi
  storageClass: longhorn

# set the type of filesystem to use: filesystem or s3
storage: filesystem

# Options for s3 storage type if .Values.storage=s3:
s3:
  bucket: my-bucket
  regionEndpoint: s3.example.com
  encrypt: false
  secure: true
  region: us-east-1
  skipverify: false

## Pass extra environment variables to the Docker Registry container.
extraEnvVars:
# - name: EXTRA_VAR_1
#  value: extra-var-value-1
# - name: EXTRA_VAR_2
#   value: extra-var-value-2

# remote url for pull-through cache 
proxy:
  remoteURL: https://registry-1.docker.io

metrics:
  enabled: false
  port: 5001
  # Create a prometheus-operator servicemonitor
  serviceMonitor:
    enabled: false

# Config to pass to 
configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
    debug:
      addr: :5001
      prometheus:
        enabled: false
        path: /metrics
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3
