# Provide opsgenie api key as a sops secret
# OVERRIDE and ENCRYPT with Sops
# or alternatively procide an existing secret "opsgenie-api-key" with key "api-key"
opsgenieApiKey: not-set

extraDashboards:
  enabled: true
  calico:
    enabled: true

# setup basicAuth for prometheus and alertmanager
# grafana is configured with oidc
basicAuth:
  enabled: true
  # htpasswd format - generate with: htpasswd -nb <user> <password>
  # OVERRIDE using sops!
  htpasswd: |
    user1:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/

# setup OIDC
# TODO setup securitypolicies for oidc for prometheus and alertmanager
oidc:
  grafana:
    enabled: true
    clientID: client-id
    clientSecret: client-secret

kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      # Do NOT add the namespace matcher to routes from AlertmanagerConfig resources
      alertmanagerConfigMatcherStrategy:
        type: None
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-cinder
            resources:
              requests:
                storage: 10Gi
    route:
      main:
        enabled: true
        hostnames: []
        #  - alertmanager.example.com
        parentRefs: []
        #  - name: envoy-gateway
        #    namespace: envoy-gateway-system
        #    sectionName: internal-https
        #    group: gateway.networking.k8s.io
        #    kind: Gateway

  grafana:
    enabled: true

    sidecar:
      # Tell Grafana to include dashboards from all namespaces
      dashboards:
        searchNamespace: ALL

    # OVERRIDE WITH STRONG grafana password using sops secret
    adminPassword: admin1234

    # OVERRIDE WITH IRIS-IAM (OIDC) clientID and clientSecret as sops secret

    route:
      main:
        enabled: true
        hostnames: []
        #  - grafana.example.com
        parentRefs: []
        #  - name: envoy-gateway
        #    namespace: envoy-gateway-system
        #    sectionName: internal-https
        #    group: gateway.networking.k8s.io
        #    kind: Gateway

    # here we reference a secret that contains oidc credentials:
    # has client_id and client_secret keys
    # this is created by providing oidc.grafana.clientID, oidc.grafana.clientSecret
    # use SOPS to encrypt those helm values when using argocd
    extraSecretMounts:
      - name: iris-iam-creds
        secretName: grafana-oidc-secret
        defaultMode: 0440
        mountPath: /etc/secrets/iris_iam_creds
        readOnly: true

    grafana.ini:
      auth.generic_oauth:
        enabled: true
        name: "IRIS IAM"
        scopes: "openid profile email"
        auth_url: "https://iris-iam.stfc.ac.uk/authorize"
        token_url: "https://iris-iam.stfc.ac.uk/token"
        api_url: "https://iris-iam.stfc.ac.uk/userinfo"
        groups_attribute_path: "groups[*]"
        allowed_groups: "stfc-cloud/team,stfc-cloud/admins"

        # these are mounted as extra secrets - see extraSecretMounts above
        client_id: $__file{/etc/secrets/iris_iam_creds/client-id}
        client_secret: $__file{/etc/secrets/iris_iam_creds/client-secret}

  prometheus-operator:
    enabled: true

  prometheus:
    enabled: true
    prometheusSpec:
      # Tell Prometheus to pick up all monitors and alerting rules, regardless of labels
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-cinder
            resources:
              requests:
                storage: 10Gi
      externalLabels:
        cluster: not-set
        env: not-set

    route:
      main:
        enabled: true
        hostnames: []
        #  - grafana.example.com
        parentRefs: []
        #  - name: envoy-gateway
        #    namespace: envoy-gateway-system
        #    sectionName: internal-https
        #    group: gateway.networking.k8s.io
        #    kind: Gateway
