# Provide opsgenie api key as a sops secret
# OVERRIDE and ENCRYPT with Sops
# or alternatively procide an existing secret "opsgenie-api-key" with key "api-key"
opsgenieApiKey: not-set

extraDashboards:
  enabled: true
  calico:
    enabled: true

# setup basicAuth for prometheus and alertmanager
# grafana is configured with oidc
basicAuth:
  enabled: true
  # htpasswd format - generate with: htpasswd -nb <user> <password>
  # OVERRIDE using sops!
  credentials: foo

# setup OIDC
# TODO setup securitypolicies for oidc for prometheus and alertmanager
oidc:
  grafana:
    enabled: true
    client_id: client-id
    client_secret: client-secret

kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-cinder

    route:
      main:
        enabled: true
        hostnames: []
        #  - alertmanager.example.com
        parentRefs: []
        #  - name: envoy-gateway
        #    namespace: envoy-gateway-system
        #    sectionName: internal-https
        #    group: gateway.networking.k8s.io
        #    kind: Gateway

  grafana:
    enabled: true

    # OVERRIDE WITH STRONG grafana password using sops secret
    adminPassword: admin1234

    # OVERRIDE WITH IRIS-IAM (OIDC) clientID and clientSecret as sops secret

    route:
      main:
        enabled: true
        hostnames: []
        #  - grafana.example.com
        parentRefs: []
        #  - name: envoy-gateway
        #    namespace: envoy-gateway-system
        #    sectionName: internal-https
        #    group: gateway.networking.k8s.io
        #    kind: Gateway

    extraSecretMounts:
      - name: iris-iam-creds
        secretName: grafana-iris-iam-creds
        defaultMode: 0440
        mountPath: /etc/secrets/iris_iam_creds
        readOnly: true

    grafana.ini:
      auth.generic_oauth:
        enabled: true
        name: "IRIS IAM"
        scopes: "openid profile email"
        auth_url: "https://iris-iam.stfc.ac.uk/authorize"
        token_url: "https://iris-iam.stfc.ac.uk/token"
        api_url: "https://iris-iam.stfc.ac.uk/userinfo"
        groups_attribute_path: "groups[*]"
        allowed_groups: "stfc-cloud/team,stfc-cloud/admins"
        client_id: $__file{/etc/secrets/iris_iam_creds/client_id}
        client_secret: $__file{/etc/secrets/iris_iam_creds/client_secret}

  prometheus-operator:
    enabled: true

  prometheus:
    enabled: true
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-cinder
      externalLabels:
        cluster: not-set
        env: not-set

    route:
      main:
        enabled: true
        hostnames: []
        #  - grafana.example.com
        parentRefs: []
        #  - name: envoy-gateway
        #    namespace: envoy-gateway-system
        #    sectionName: internal-https
        #    group: gateway.networking.k8s.io
        #    kind: Gateway
