apiVersion: v2
dependencies:
  - name: cert-manager
    repository: oci://quay.io/jetstack/charts
    version: v1.20.3
  - name: trust-manager
    repository: oci://quay.io/jetstack/charts
    version: 0.24.0
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 2.2.12
description: A Helm chart to deploy opinionated instance of cert-manager for the STFC Cloud
name: stfc-cloud-cert-manager
type: application
version: 2.3.0
