{
 "title": "Harbor",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Harbor instance",
    "query": {
     "query": "label_values(harbor_system_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Components Status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "harbor_up", "legendFormat": "{{component}}" }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(harbor_health{instance=~\"$instance\", job=\"harbor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total projects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min by (public) (harbor_project_total{job=\"harbor\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage used",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(harbor_statistics_total_storage_consumption{instance=~\"$instance\"}) / sum(harbor_health{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (public) (harbor_project_total{job=\"harbor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New projects last 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(harbor_project_total{instance=~\"$instance\", job=\"harbor\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project Image Pull Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(harbor_artifact_pulled{instance=~\"$instance\"}) by (project_name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories by project",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_name) (harbor_project_repo_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota usage by project",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_name) (harbor_project_quota_usage_byte{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artifacts pulled by project",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(project_name) (harbor_artifact_pulled{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total core requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(harbor_core_http_request_total[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Current load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "harbor_core_http_inflight_requests",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API request time 0.9",
   "type": "timeseries",
   "description": "The time duration of the requests",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Total requests duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 27 },
   "targets": [
    {
     "expr": "sum by (method) (harbor_core_http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Request Rate By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(harbor_core_http_request_total{job=\"harbor\"}) by (method,operation)) - sum(harbor_core_http_request_total{job=\"harbor\"} offset 1m) by (method,operation)",
     "legendFormat": "{{method}} : {{operation}}"
    }
   ]
  },
  {
   "title": "Core Request Latency By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(harbor_core_http_request_duration_seconds{job=\"harbor\",quantile=\"0.99\"}) by (method,operation)",
     "legendFormat": "{{method}} : {{operation}}"
    }
   ]
  },
  {
   "title": "JobService Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task latency",
     "type": "timeseries",
     "description": "when a task is scheduled into a queue - this helps us see how long that task has been waiting before picked up for execution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "harbor_task_queue_latency{job=\"harbor\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Task concurrency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "harbor_task_concurrency{job=\"harbor\"}"
      }
     ]
    },
    {
     "title": "Task queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "harbor_task_queue_size{job=\"harbor\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Task process time 0.9",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{job=\"harbor\", quantile=\"0.9\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Tasks per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "targets": [
      {
       "expr": "rate(harbor_jobservice_task_total{job=\"harbor\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Number of running scheduled job",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "targets": [
      {
       "expr": "harbor_task_scheduled_total{job=\"harbor\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Registry request inflight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "registry_http_in_flight_requests{job=\"harbor\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Total Registry request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(registry_http_requests_total{job=\"harbor\"}[5m])",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Registry storage cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(registry_storage_cache_total{job=\"harbor\"}[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Registry request time 0.9",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_request_duration_seconds_bucket{job=\"harbor\"}[10m]))",
       "legendFormat": "{{method}} - {{handler}}"
      }
     ]
    }
   ]
  }
 ]
}