_meta:
  type: "rolesmapping"
  config_version: 2

# Admin role mapping
admin_role:
  reserved: true
  backend_roles:
    - "admin"
    - "stfc-cloud/admins"
  description: "Maps admin backend role to admin_role"

# all-access role mapping
all_access:
  reserved: true
  backend_roles:
    - "admin"
    - "stfc-cloud/admins"
  description: "Maps admin backend role to admin_role"

# Cloud staging writer role mapping
writer_staging_role:
  reserved: false
  backend_roles:
    - "writer_staging_role"
  description: "Maps writer-staging user to cloud-staging tenant write access"

# Cloud production writer role mapping
writer_prod_role:
  reserved: false
  backend_roles:
    - "writer_prod_role"
  description: "Maps writer-prod user to cloud tenant write access"

# Cloud staging reader role mapping
reader_staging_role:
  reserved: false
  backend_roles:
    - "reader_staging_role"
    - "stfc-cloud/team"
  description: "Maps reader-staging user to cloud-staging and azimuth-staging read access"

# Azimuth production writer role mapping
writer_azimuth_user_prod_role:
  reserved: false
  backend_roles:
    - "writer_azimuth_user_prod_role"
  description: "Maps writer-azimuth-user-prod to azimuth tenant write access"

# Azimuth staging writer role mapping
writer_azimuth_user_staging_role:
  reserved: false
  backend_roles:
    - "writer_azimuth_user_staging_role"
  description: "Maps writer-azimuth-user-staging to azimuth-staging tenant write access"
