harbor:
  fullnameOverride: harbor

  externalURL: "https://harbor.example.com"

  internalTLS:
    enabled: true
    certSource: secret
    core:
      secretName: "harbor-core-tls"
    jobservice:
      secretName: "harbor-jobservice-tls"
    registry:
      secretName: "harbor-registry-tls"
    portal:
      secretName: "harbor-portal-tls"
    trivy:
      secretName: "harbor-trivy-tls"

  expose:
    type: route
    tls:
      # keep this disabled for gateway proxy and setup your own tls termination on gateway layer
      enabled: false

    route:
      enabled: true
      labels: {}
      annotations: {}
      # References to the parent gateways
      parentRefs: []
        # - name: envoy-internal
        #   namespace: networking
        #   sectionName: https
        #   group: gateway.networking.k8s.io
        #   kind: Gateway
      # The hostnames for the HTTPRoute
      hosts: []
        # - "harbor.example.com"

  database:
    type: external
    external:
      host: "host.example.com"
      port: "5432"
      coreDatabase: "harbor_registry"
      username: "registry_user"
      # if using existing secret, the key must be "password"
      # OVERRIDE and Encrypt this as SOP key
      password: "password"
      # "disable" - No SSL
      # "require" - Always SSL (skip verification)
      # "verify-ca" - Always SSL (verify that the certificate presented by the
      # server was signed by a trusted CA)
      # "verify-full" - Always SSL (verify that the certification presented by the
      # server was signed by a trusted CA and the server host name matches the one
      # in the certificate)
      sslmode: "disable"
    # The maximum number of connections in the idle connection pool per pod (core+exporter).
    # If it <=0, no idle connections are retained.
    maxIdleConns: 100
    # The maximum number of open connections to the database per pod (core+exporter).
    # If it <= 0, then there is no limit on the number of open connections.
    # Note: the default number of connections is 1024 for postgre of harbor.
    maxOpenConns: 900
    ## Additional deployment annotations
    podAnnotations: {}
    ## Additional deployment labels
    podLabels: {}

  jobservice:
    replicas: 2
    jobLoggers:
      - database

  registry:
    replicas: 2

  trivy:
    replicas: 2

  exporter:
    replicas: 2

  portal:
    replicas: 2

  core:
    replicas: 2

  persistence:
    resourcePolicy: ""
    imageChartStorage:
      type: s3
      s3:
        bucket: bucketname
        # OVERRIDE and Encrypt these as SOPs keys
        accesskey: awsaccesskey
        secretkey: awssecretkey

        regionendpoint: s3.example.com
        encrypt: false
        secure: true
        skipverify: false

  metrics:
    enabled: true
    rules:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus

backup:
  enabled: true
  image: amazon/aws-cli:latest
  endpoint: "https://s3.example.com"
  sourceBucket: "s3://harbor-source-bucket"
  # OVERRIDE and Encrypt these as SOPs keys
  accesskey: awsaccesskey
  secretkey: awssecretkey

  destination:
    daily: "s3://harbor-destination-backup/daily"
    weekly: "s3://harbor-destination-backup/weekly"
    monthly: "s3://harbor-destination-backup/monthly"

  schedule:
    daily: "12 12 * * *" # Every day @ 12:12 (add smear)
    weekly: "2 9 * * 1" # Every Monday @ 9:02
    monthly: "17 16 1 * *" # 1st of month @ 16:17


# internal cluster issuer to generate internal certs (default internal-ca)
# internalCertIssuer: ""

# internal trust-manager bundle, to expose internal CA cert for backendtlspolicy verification (default internal-bundle)
# caBundleName: ""
