{{- if index .Values "cert-manager" "le-prod" "enabled" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: cloud-support@stfc.ac.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod-account-key
    solvers:
    - http01:
        ingress:
          # Assuming you have used the CAPI Addons Ingress Controller
          ingressClassName: nginx
{{- end }}
