apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values "opensearch-cluster").cluster.security.config.adminCredentialsSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    username: {{ .Values.admin.username }}
    password: {{ .Values.admin.password }}