{{- if .Values.httproute.opensearch.enabled -}}
{{- $clusterName := include "opensearch-cluster.cluster-name" (index .Subcharts "opensearch-cluster") -}}
{{- $servicePort := (index .Values "opensearch-cluster").cluster.general.httpPort -}}
{{- $serviceName := (index .Values "opensearch-cluster").cluster.general.serviceName | default $clusterName }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $serviceName }}-httproute
  labels:
    {{- include "opensearch-cluster.labels" (index .Subcharts "opensearch-cluster") | nindent 4 }}
  {{- with .Values.httproute.opensearch.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.httproute.opensearch.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httproute.opensearch.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.httproute.dashboards.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .timeouts }}
      timeouts:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ $serviceName }}
          port: {{ $servicePort }}
    {{- end }}

{{- end }}