# not used by default
# TODO find a better place for this

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-opensearch
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  migratable: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer