apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values "opensearch-cluster").cluster.name }}-securityconfig-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- $defaultFiles := dict
      "config.yml" (.Files.Get "include/config.yml")
      "roles.yml" (.Files.Get "include/roles.yml")
      "roles_mapping.yml" (.Files.Get "include/roles_mapping.yml")      
      "tenants.yml" (.Files.Get "include/tenants.yml")
  }}

  {{- $customFiles := .Values.customSecurityConfigFiles | default dict }}

  {{- $merged := merge $defaultFiles $customFiles }}

  {{- range $filename, $content := $merged }}
  {{ $filename }}: {{ $content | b64enc | quote }}
  {{- end }}