apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values "opensearch-cluster").cluster.name }}-securityconfig-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if .Values.customSecurityConfigFiles }}
  {{- range $filename, $content := .Values.customSecurityConfigFiles }}
  {{ $filename }}: {{ $content | b64enc | quote }}
  {{- end }}
  {{- else }}
    config.yml: {{ .Files.Get "include/config.yaml" | b64enc | quote }}
    roles.yml: {{ .Files.Get "include/roles.yaml" | b64enc | quote }}
    roles_mapping.yml: {{ .Files.Get "include/roles_mapping.yaml" | b64enc | quote }}
    internal_users.yml: {{ .Files.Get "include/internal_users.yaml" | b64enc | quote }}
    tenants.yml: {{ .Files.Get "include/tenants.yaml" | b64enc | quote }}
  {{- end }}