{{- if .Values.basicAuth.enabled }}
{{- if (index .Values "kube-prometheus-stack").prometheus.enabled -}}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: basicauth-prometheus
  namespace: {{.Release.Namespace}}
  labels:
    monitoring-auth/type: basic-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{.Release.Name}}-kube-prom-prometheus
  basicAuth:
    users:
      group: ""
      kind: Secret
      name: internal-basic-auth
      namespace: {{.Release.Namespace}}
{{ end }}
---
{{- if (index .Values "kube-prometheus-stack").alertmanager.enabled -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: basicauth-alertmanager
  namespace: {{.Release.Namespace}}
  labels:
    monitoring-auth/type: basic-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{.Release.Name}}-kube-prom-alertmanager
  basicAuth:
    users:
      group: ""
      kind: Secret
      name: internal-basic-auth
      namespace: {{.Release.Namespace}}
{{- end }}
{{- end }}
