{{- if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: internal-basic-auth
  namespace: monitoring-system
type: Opaque
stringData:
  # htpasswd format - generate with: htpasswd -nb <user> <password>
  .htpasswd: |
{{ .Values.basicAuth.htpasswd | indent 4 }}
{{- end }}