
{{- if .Values.oidc.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client-id: {{ .Values.oidc.grafana.clientID | quote }}
  client-secret: {{ .Values.oidc.grafana.clientSecret | quote }}
{{- end }}

# TODO add oidc secrets for prometheus and alertmanager