{{- if .Values.external.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "envoy-gateways.name" . }}-external
  namespace: {{ include "envoy-gateways.namespace" . }}
  labels:
    app.kubernetes.io/component: gateway-external
  annotations:
    # cert-manager creates certs specified for each tls secret in specified listeners 
    cert-manager.io/cluster-issuer: {{ .Values.external.clusterIssuerName }}
spec:
  gatewayClassName: external
  listeners:
    {{- range .Values.external.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname }}
      {{- end }}
      {{- if .tlsSecret }}
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ .tlsSecret }}
        mode: {{ .tlsMode }}
      {{- end }}
      {{- if .allowedRoutes }}
      allowedRoutes:
        {{- toYaml .allowedRoutes | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}