opensearch-operator:
  nameOverride: op
  installCRDs: true

opensearch-cluster:
  cluster:
    # change this to match name of cluster you want
    name: log-storage

    # -- Opensearch nodes configuration
    nodePools:
      - component: nodes
        diskSize: "30Gi"
        replicas: 3
        roles:
          - "master"
          - "data"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        persistence:
          pvc:
            storageClass: csi-cinder
            accessModes: 
              - ReadWriteOnce

    general:
      # disable for now whilst testing
      monitoring:
        enable: false
      
      # setup snapshotting onto S3 
      snapshotRepositories: []

      # https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#smartscaler
      useSmartScaler: false
    
    dashboards:
      enable: true
      tls: 
        enable: true
        generate: true

      additionalConfig: 
        opensearch_security.multitenancy.enabled: "true"
        opensearch_security.cookie.secure: "true"

        # enable this if you want iris-iam authentication
        
        # opensearch_security.auth.type: ["basicauth", "openid"]
        # opensearch_security.auth.multiple_auth_enabled: "true"
        # opensearch_security.openid.connect_url: "https://iris-iam.stfc.ac.uk/.well-known/openid-configuration"
        # opensearch_security.openid.scope: "openid profile email preferred_username groups"
        # opensearch_security.openid.base_redirect_url: https://opensearch.example.com

    ingress:
      opensearch:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        className: nginx
        hosts:
          - host: opensearch.example.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: opensearch-tls
            hosts:
              - opensearch.example.com

      dashboards:
        opensearchCredentialsSecret: opensearch-admin-credentials

        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        className: nginx
        hosts:
          - host: opensearch-dashboards.example.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: opensearch-tls
            hosts:
              - opensearch-dashboards.example.com
        
    security:
      config: 
        adminCredentialsSecret: opensearch-admin-credentials
  
  # define roles here
  # https://opensearch.org/docs/latest/security/configuration/yaml/#rolesyml
  roles:
  # - name: writer_role
  #   allowedActions:
  #     - "indices:data/write/index"
  #     - "indices:data/write/bulk"
  #     - "indices:data/write/update"
  #     - "indices:data/write/delete"
  #     - "indices:data/write/create"
  # - name: writer_role_for_index_pattern
  #   indexPermissions:
  #     indexPatterns:
  #       - logs*
  #     allowedActions:
  #      - "indices:data/write/index"
  #      - "indices:data/write/bulk"
  #      - "indices:data/write/update"
  #      - "indices:data/write/delete"
  #      - "indices:data/write/create"
  # - name: writer_role_with_tenant_scope
  #   tenantPermissions:
  #     tenantPatterns:
  #       - azimuth*
  #     allowedActions:
  #      - "indices:data/write/index"
  #      - "indices:data/write/bulk"
  #      - "indices:data/write/update"
  #      - "indices:data/write/delete"
  #      - "indices:data/write/create"

  # define new internal users here
  #https://opensearch.org/docs/latest/security/configuration/yaml/#internal_usersyml
  # recommended to setup reserved users here - those that can't be changed using the REST API or OpenSearch Dashboards
  users:
  # - name: fluentbit
  #   # THIS SHOULD BE A SECRET - set it in secret-template.yaml
  #   secretName: foo 
  #   secretKey: bar
  #   backendRoles:
  #    - "kibana_user"

  # define rolemappings here 
  # https://opensearch.org/docs/latest/security/configuration/yaml/#roles_mappingyml
  # you can map iris-iam groups to roles here 
  usersRoleBinding: 
  #  - name: admin_access
  #    users:
  #     - example1
  #     - example2
  #    roles:
  #     - admin
  #    roles:
  #     - stfc-cloud/admins

  # define custom tenants here - multi-tenancy is always enabled 
  # https://opensearch.org/docs/latest/security/configuration/yaml/#tenantsyml
  # more about tenants - https://opensearch.org/docs/latest/security/multi-tenancy/tenant-index
  tenants:
    # - name: prod_tenant
    #   description: "tenant for production logs"

  # define aliases for groups of opensearch actions here
  actionGroups:
    #  myactiongroup:
    #   reserved: false
    #   hidden: false
    #   allowed_actions:
    #   - "indices:data/write/index*"
    #   - "indices:data/write/update*"
    #   - "indices:admin/mapping/put"
    #   - "indices:data/write/bulk*"
    #   - "read"
    #   - "write"
    #   static: false

  # define index templates as IAC
  # https://docs.opensearch.org/docs/latest/im-plugin/index-templates/
  indexTemplates:
  # - name: logs-index-template
  #   indexPatterns:
  #     - "logs*"
  #   dataStream: null # optional
  #    composedOf: # optional
  #      - example-component-template
  #    priority: 100 # optional
  #    templateSpec: {} # optional
  #    version: 1 # optional
  #    _meta: {} # optional


  # define index state management policies
  # https://docs.opensearch.org/docs/latest/im-plugin/ism/index/
  ismPolicies:
#    - name: retention-90d
#      defaultState: hot
#      description: log retention 90 days
#      states:
#        - name: hot
#          actions:
#            - replicaCount: 
#                numberOfReplicas: 1
#          transitions: 
#            - stateName: delete
#              conditions:
#                minIndexAge: "90d"
#        - name: delete
#          actions: 
#           - delete
#          transitions: {}
