name: lint stfc-azimuth-llm-chat chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/azimuth_llm_chat_chart.yaml"
      - "charts/stfc-azimuth-llm-chat/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm dependency update charts/stfc-azimuth-llm-chat/.
          helm lint charts/stfc-azimuth-llm-chat --strict=true
