name: lint stfc-cloud-logging chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/logging_chart.yaml"
      - "charts/stfc-cloud-logging/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          cp charts/stfc-cloud-logging/secret-values.yaml.template /tmp/secret-values.yaml
          helm dependency update charts/stfc-cloud-logging/.
          helm lint charts/stfc-cloud-logging --values charts/stfc-cloud-logging/values.yaml --values /tmp/secret-values.yaml --strict=true
